<script setup>
import { onMounted, ref, watch } from "vue";
import { fetchFeedback, fetchFeedbackItem, updateFeedback } from "../api.js";

const props = defineProps({ active: { type: Boolean, default: false }, admin: { type: Boolean, default: false } });
const emit = defineEmits(["toast"]);
const rows = ref([]); const total = ref(0); const page = ref(1); const pageSize = 50; const selected = ref(null); const loading = ref(false); const error = ref(""); const saving = ref(false);
const filters = ref({ status: "", category: "", node_id: "" });
const draft = ref({ status: "open", reply: "" });
const labels = { open: "待处理", in_progress: "处理中", resolved: "已解决", closed: "已关闭" };
const categoryLabels = { bug: "问题", suggestion: "建议", other: "其他" };
function unwrap(v) { return v?.feedback || v?.item || v || null; }
function row(v) { return unwrap(v); }
function syncUrl(id = "", nodeId = "") { const u = new URL(window.location.href); if (id) u.searchParams.set("feedback_id", id); else u.searchParams.delete("feedback_id"); if (nodeId) u.searchParams.set("feedback_node_id", nodeId); else u.searchParams.delete("feedback_node_id"); window.history.replaceState({}, "", `${u.pathname}${u.search}${u.hash}`); }
function urlId() { return new URLSearchParams(window.location.search).get("feedback_id") || ""; }
function urlNodeId() { return new URLSearchParams(window.location.search).get("feedback_node_id") || ""; }
async function load() { if (!props.admin) return; loading.value = true; error.value = ""; try { const data = await fetchFeedback({ ...filters.value, page: page.value, page_size: pageSize }); rows.value = (Array.isArray(data) ? data : data?.items || data?.feedback || []).map(row); total.value = Number(data?.total || rows.value.length); const id = urlId(); if (id) await open({ client_feedback_id: id, node_id: urlNodeId() }); } catch (e) { error.value = e.message || "无法加载反馈"; } finally { loading.value = false; } }
async function open(item) { const id = row(item)?.client_feedback_id; const nodeId = row(item)?.node_id || urlNodeId(); if (!id || !nodeId) { error.value = "反馈详情缺少来源 Node，无法安全定位"; return; } try { selected.value = row(await fetchFeedbackItem(id, nodeId)); draft.value = { status: selected.value.status || "open", reply: selected.value.reply || "" }; syncUrl(id, nodeId); } catch (e) { error.value = e.message || "无法加载详情"; } }
async function save() { if (!selected.value) return; saving.value = true; error.value = ""; try { selected.value = row(await updateFeedback(selected.value.client_feedback_id, { status: draft.value.status, reply: draft.value.reply, revision: selected.value.revision }, selected.value.node_id)); emit("toast", { message: "反馈已更新", type: "success" }); await load(); } catch (e) { if (e.status === 409) error.value = "反馈已被其他管理员更新，请刷新详情后再保存"; else error.value = e.message || "保存失败"; } finally { saving.value = false; } }
watch(() => props.active, (v) => { if (v) void load(); }); onMounted(() => { if (props.active) void load(); });
</script>
<template>
  <div class="feedback-view">
    <div class="feedback-toolbar"><label>处理状态<select v-model="filters.status" @change="page=1;load()"><option value="">全部</option><option value="open">待处理</option><option value="in_progress">处理中</option><option value="resolved">已解决</option><option value="closed">已关闭</option></select></label><label>类型<select v-model="filters.category" @change="page=1;load()"><option value="">全部</option><option value="bug">问题</option><option value="suggestion">建议</option><option value="other">其他</option></select></label><label>Node<input v-model="filters.node_id" placeholder="Node ID" @keyup.enter="page=1;load()" /></label><button class="btn btn-ghost" type="button" @click="load">刷新</button></div>
    <p v-if="error" class="feedback-error" role="alert">{{ error }}</p>
    <div class="feedback-columns" :class="{ 'feedback-columns--empty': !loading && !rows.length }"><section class="feedback-inbox"><p v-if="loading" class="feedback-empty">正在加载…</p><p v-else-if="!rows.length" class="feedback-empty">暂无反馈</p><button v-for="item in rows" :key="`${item.node_id}:${item.client_feedback_id}`" type="button" class="feedback-inbox__row" :class="{ active: selected?.client_feedback_id === item.client_feedback_id && selected?.node_id === item.node_id }" @click="open(item)"><strong>{{ item.title || "无标题" }}</strong><small>{{ item.node_id || "未知 Node" }} · {{ labels[item.status] || "待处理" }}</small></button><div v-if="total > pageSize" class="feedback-pages"><button class="btn btn-ghost" :disabled="page<=1" @click="page--;load()">上一页</button><span>第 {{ page }} / {{ Math.ceil(total / pageSize) }} 页</span><button class="btn btn-ghost" :disabled="page>=Math.ceil(total/pageSize)" @click="page++;load()">下一页</button></div></section><section v-if="selected" class="feedback-detail"><div class="feedback-detail__head"><div><h2>{{ selected.title }}</h2><small>{{ selected.client_feedback_id }} · {{ categoryLabels[selected.category] || "其他" }}</small></div><button class="btn btn-ghost" type="button" @click="open(selected)">刷新详情</button></div><pre>{{ selected.body }}</pre><p class="feedback-source">来源 Node: {{ selected.node_id || "—" }} | 创建: {{ selected.created_at || "—" }}</p><label>处理状态<select v-model="draft.status"><option value="open">待处理</option><option value="in_progress">处理中</option><option value="resolved">已解决</option><option value="closed">已关闭</option></select></label><label>回复<textarea v-model="draft.reply" rows="6" placeholder="回复会同步回 Node" /></label><button class="btn btn-primary" type="button" :disabled="saving" @click="save">{{ saving ? "保存中…" : "保存处理结果" }}</button></section><section v-else-if="rows.length" class="feedback-detail feedback-detail--empty"><p>选择左侧一条反馈查看详情</p></section></div>
  </div>
</template>
<style scoped>
.feedback-toolbar { display:flex; align-items:end; flex-wrap:wrap; gap:12px; padding:14px 0; border-bottom:1px solid var(--border); }.feedback-toolbar label,.feedback-detail label { display:grid; gap:5px; color:var(--text-muted); font-size:12px; }.feedback-toolbar input,.feedback-toolbar select,.feedback-detail select,.feedback-detail textarea { border:1px solid var(--border); border-radius:6px; padding:8px; background:var(--bg-surface); color:var(--text); font:inherit; }.feedback-columns { display:grid; grid-template-columns:minmax(260px, .8fr) minmax(420px, 1.5fr); gap:20px; margin-top:18px; }.feedback-inbox { border:1px solid var(--border); border-radius:8px; overflow:hidden; }.feedback-inbox__row { display:grid; gap:5px; width:100%; padding:14px; border:0; border-bottom:1px solid var(--border); background:var(--bg-surface); color:var(--text); text-align:left; cursor:pointer; }.feedback-inbox__row.active,.feedback-inbox__row:hover { background:var(--bg-hover); }.feedback-inbox__row small,.feedback-detail small,.feedback-source { color:var(--text-muted); }.feedback-detail { display:grid; align-content:start; gap:12px; }.feedback-detail__head { display:flex; justify-content:space-between; gap:12px; }.feedback-detail h2 { margin:0; font-size:18px; }.feedback-detail pre { white-space:pre-wrap; overflow-wrap:anywhere; margin:0; padding:14px; border-radius:6px; background:var(--bg-muted); font:inherit; line-height:1.55; }.feedback-detail textarea { resize:vertical; }.feedback-error { color:var(--danger); }@media(max-width:800px){.feedback-columns{grid-template-columns:1fr;}}
 .feedback-toolbar { border: 1px solid var(--border); border-radius: 8px; background: var(--bg-surface); padding: 18px 20px; } .feedback-columns--empty { grid-template-columns: 1fr; } .feedback-columns--empty .feedback-inbox { min-height: 220px; } .feedback-empty, .feedback-detail--empty { display: grid; place-items: center; min-height: 180px; margin: 0; padding: 28px; color: var(--text-muted); text-align: center; } .feedback-detail--empty { border: 1px dashed var(--border); border-radius: 8px; background: var(--bg-muted); } .feedback-detail__head > div { min-width: 0; overflow-wrap: anywhere; } .feedback-detail__head .btn { align-self: start; flex-shrink: 0; } .feedback-detail h2 { overflow-wrap: anywhere; }
</style>
