package tools

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"os/exec"
	"sort"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

// ExecutionTarget identifies the execution world selected by the policy and
// orchestration layers. The local provider is the first implementation; the
// target fields leave room for SSH, container, and exec-server providers
// without changing the model-facing bash_run schema.
type ExecutionTarget struct {
	Kind string
	ID   string
}

const executionTargetLocal = "local"

// ExecutionContext carries the correlation fields needed by execution
// events. It is deliberately separate from the model-facing tool arguments.
type ExecutionContext struct {
	AgentID         string
	SessionID       string
	TurnID          string
	ToolCallID      string
	BackgroundJobID string
	Target          ExecutionTarget
	PolicyDecision  string
	ApprovalID      string
	RiskLevel       string
	CommandDigest   string
}

// RemoteProcessRecovery identifies a remote process group without storing the
// command or credentials. The token is generated by Node and must match the
// token written by the remote wrapper before cleanup is attempted.
type RemoteProcessRecovery struct {
	TargetID string
	JobToken string
	PIDFile  string
}

// ExecRequest is the internal request passed from a tool to an execution
// provider. Command keeps shell syntax (pipelines, redirects, and scripts),
// while Argv is reserved for future direct process execution.
type ExecRequest struct {
	Target         ExecutionTarget
	Context        ExecutionContext
	ShellType      string
	Command        string
	Argv           []string
	CWD            string
	Env            map[string]string
	Environment    EnvironmentPolicy
	TTY            bool
	PipeStdin      bool
	Timeout        time.Duration
	MaxOutputBytes int
	EventSink      ProcessEventSink
}

// EnvironmentPolicy controls which Node environment variables cross the
// local execution boundary. The zero value is scrub, which preserves the
// existing safe default. Set and ExecRequest.Env are explicit values and are
// applied after inherited values, with Env taking precedence over Set.
type EnvironmentPolicyMode string

const (
	EnvironmentPolicyInherit EnvironmentPolicyMode = "inherit"
	EnvironmentPolicyScrub   EnvironmentPolicyMode = "scrub"
	EnvironmentPolicyAllow   EnvironmentPolicyMode = "allow"
	EnvironmentPolicySet     EnvironmentPolicyMode = "set"
)

type EnvironmentPolicy struct {
	Mode  EnvironmentPolicyMode
	Allow []string
	Set   map[string]string
}

// TargetStageStatus describes one observable connection/test phase.
type TargetStageStatus struct {
	Name       string `json:"name"`
	Status     string `json:"status"`
	Code       string `json:"code,omitempty"`
	Message    string `json:"message,omitempty"`
	DurationMS int64  `json:"duration_ms"`
}

// TargetStatus describes provider reachability and diagnostic phases. The
// original Available/Message fields remain stable for existing callers.
type TargetStatus struct {
	Available bool                `json:"available"`
	Message   string              `json:"message"`
	ErrorCode string              `json:"error_code,omitempty"`
	Stages    []TargetStageStatus `json:"stages,omitempty"`
}

type ProcessEventType string

const (
	ProcessEventStarted            ProcessEventType = "process_started"
	ProcessEventOutput             ProcessEventType = "process_output"
	ProcessEventTerminateRequested ProcessEventType = "process_terminate_requested"
	ProcessEventExited             ProcessEventType = "process_exited"
)

// ExitStatus is independent of os.ProcessState so remote providers can expose
// the same lifecycle event without pretending to have a local process.
type ExitStatus struct {
	Code  int
	Error string
}

// ProcessEvent is a runtime execution event. Seq is monotonic per process;
// output bytes are kept separate by Stream and are not mixed with stderr.
type ProcessEvent struct {
	Type        ProcessEventType
	ProcessID   string
	Seq         uint64
	Context     ExecutionContext
	Stream      string
	Data        []byte
	OutputBytes int64
	Exit        *ExitStatus
}

type ProcessEventSink func(ProcessEvent)

// Process is the provider-neutral lifecycle handle used by synchronous and
// background shell execution. Pipes are acquired before Start so callers can
// keep the current stdout/stderr collection and auto-degrade behavior.
type Process interface {
	ID() string
	StdoutPipe() (io.ReadCloser, error)
	StderrPipe() (io.ReadCloser, error)
	SetOutput(stdout, stderr io.Writer)
	Start() error
	Wait() error
	ExitStatus() *ExitStatus
	Terminate(ctx context.Context) error
	Close() error
}

// ShellProvider creates process handles for a selected execution target.
// Policy, HITL, history, and tool-result formatting remain outside providers.
type ShellProvider interface {
	Start(ctx context.Context, req ExecRequest) (Process, error)
	Test(ctx context.Context, target ExecutionTarget) (TargetStatus, error)
}

// LocalShellProvider executes a shell command on the current Node host. It
// owns only process construction and lifecycle; bash_run still owns timeout,
// output decoding, compression, and background-job semantics.
type LocalShellProvider struct{}

var localProcessSequence uint64

func NewLocalShellProvider() *LocalShellProvider {
	return &LocalShellProvider{}
}

func (p *LocalShellProvider) Start(_ context.Context, req ExecRequest) (Process, error) {
	if target := req.Target.Kind; target != "" && target != executionTargetLocal {
		return nil, fmt.Errorf("local shell provider does not support target %q", target)
	}
	if req.TTY {
		return nil, fmt.Errorf("local shell provider does not support TTY yet")
	}
	if req.PipeStdin {
		return nil, fmt.Errorf("local shell provider does not support piped stdin yet")
	}
	if strings.TrimSpace(req.Command) == "" && len(req.Argv) == 0 {
		return nil, fmt.Errorf("execution command is required")
	}
	if strings.TrimSpace(req.Command) != "" && len(req.Argv) > 0 {
		return nil, fmt.Errorf("execution request cannot contain both command and argv")
	}

	var cmd *exec.Cmd
	var err error
	if len(req.Argv) > 0 {
		cmd = exec.Command(req.Argv[0], req.Argv[1:]...)
	} else {
		var shellType *string
		if strings.TrimSpace(req.ShellType) != "" {
			value := req.ShellType
			shellType = &value
		}
		st, resolveErr := resolveShellType(shellType)
		if resolveErr != nil {
			return nil, resolveErr
		}
		cmd, err = buildShellCommand(st, req.Command)
		if err != nil {
			return nil, err
		}
	}
	applyShellCmdDir(cmd, req.CWD)
	// Always set an explicit environment. Leaving cmd.Env nil makes os/exec
	// inherit every Node process variable, including API keys and credentials.
	cmd.Env, err = buildShellEnvironment(req.Env, req.Environment)
	if err != nil {
		return nil, err
	}

	seq := atomic.AddUint64(&localProcessSequence, 1)
	return &localProcess{
		id:   fmt.Sprintf("local-process-%d", seq),
		cmd:  cmd,
		ctx:  req.Context,
		sink: req.EventSink,
	}, nil
}

var scrubbedShellEnvironmentNames = map[string]struct{}{
	"ACCESS_KEY": {}, "API_KEY": {}, "AUTH": {}, "CLIENT_SECRET": {},
	"CREDENTIAL": {}, "PASSWORD": {}, "PASSWD": {}, "PRIVATE_KEY": {},
	"SECRET": {}, "TOKEN": {}, "COOKIE": {}, "DSN": {}, "KEY": {},
}

// buildShellEnvironment applies an explicit environment policy. Values set by
// the request are always intentional and are added after inherited values.
func buildShellEnvironment(extra map[string]string, policy EnvironmentPolicy) ([]string, error) {
	mode := strings.ToLower(strings.TrimSpace(string(policy.Mode)))
	if mode == "" {
		mode = string(EnvironmentPolicyScrub)
	}
	switch EnvironmentPolicyMode(mode) {
	case EnvironmentPolicyInherit, EnvironmentPolicyScrub, EnvironmentPolicyAllow, EnvironmentPolicySet:
	default:
		return nil, fmt.Errorf("unsupported environment policy %q", policy.Mode)
	}
	values := make(map[string]string)
	for key, value := range policy.Set {
		if err := validateEnvironmentAssignment(key, value); err != nil {
			return nil, err
		}
		values[key] = value
	}
	for key, value := range extra {
		if err := validateEnvironmentAssignment(key, value); err != nil {
			return nil, err
		}
		values[key] = value
	}

	allowed := make(map[string]struct{}, len(policy.Allow))
	for _, key := range policy.Allow {
		key = strings.TrimSpace(key)
		if key == "" {
			continue
		}
		if !validEnvName(key) {
			return nil, fmt.Errorf("invalid environment allow name %q", key)
		}
		allowed[key] = struct{}{}
	}
	if mode != string(EnvironmentPolicySet) {
		for _, item := range os.Environ() {
			key, value, ok := strings.Cut(item, "=")
			if !ok {
				continue
			}
			if mode == string(EnvironmentPolicyScrub) && shouldScrubShellEnvironmentName(key) {
				continue
			}
			if mode == string(EnvironmentPolicyAllow) {
				if _, ok := allowed[key]; !ok {
					continue
				}
			}
			values[key] = value
		}
	}
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	out := make([]string, 0, len(keys))
	for _, key := range keys {
		out = append(out, key+"="+values[key])
	}
	return out, nil
}

func validateEnvironmentAssignment(key, value string) error {
	if !validEnvName(key) {
		return fmt.Errorf("invalid environment variable %q", key)
	}
	if strings.ContainsRune(value, '\x00') {
		return fmt.Errorf("environment variable %q contains NUL", key)
	}
	return nil
}

// scrubbedShellEnvironment keeps the existing helper contract for callers
// that only need the default policy.
func scrubbedShellEnvironment(extra map[string]string) []string {
	values, err := buildShellEnvironment(extra, EnvironmentPolicy{Mode: EnvironmentPolicyScrub})
	if err != nil {
		return nil
	}
	return values
}

func shouldScrubShellEnvironmentName(name string) bool {
	upper := strings.ToUpper(strings.TrimSpace(name))
	if upper == "" || strings.HasPrefix(upper, "DAGENTS_") || strings.HasPrefix(upper, "CODEX_") {
		return true
	}
	parts := strings.FieldsFunc(upper, func(r rune) bool {
		return !((r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9'))
	})
	for _, part := range parts {
		if _, ok := scrubbedShellEnvironmentNames[part]; ok {
			return true
		}
	}
	for compound := range scrubbedShellEnvironmentNames {
		if strings.Contains(compound, "_") && (upper == compound || strings.Contains(upper, "_"+compound) || strings.Contains(upper, compound+"_")) {
			return true
		}
	}
	return false
}

func (p *LocalShellProvider) Test(ctx context.Context, target ExecutionTarget) (TargetStatus, error) {
	if ctx != nil {
		select {
		case <-ctx.Done():
			return TargetStatus{}, ctx.Err()
		default:
		}
	}
	if target.Kind != "" && target.Kind != executionTargetLocal {
		return TargetStatus{Message: fmt.Sprintf("unsupported target %q", target.Kind)}, nil
	}
	return TargetStatus{Available: true, Message: "local execution is available"}, nil
}

type localProcess struct {
	mu          sync.Mutex
	id          string
	cmd         *exec.Cmd
	tree        processTreeHandle
	ctx         ExecutionContext
	sink        ProcessEventSink
	seq         uint64
	eventMu     sync.Mutex
	start       bool
	close       bool
	exitMu      sync.RWMutex
	exit        *ExitStatus
	outputBytes int64
}

func (p *localProcess) ID() string {
	if p == nil {
		return ""
	}
	return p.id
}

func (p *localProcess) StdoutPipe() (io.ReadCloser, error) {
	if p == nil || p.cmd == nil {
		return nil, fmt.Errorf("process is nil")
	}
	pipe, err := p.cmd.StdoutPipe()
	if err != nil {
		return nil, err
	}
	return &processEventReader{ReadCloser: pipe, process: p, stream: "stdout"}, nil
}

func (p *localProcess) StderrPipe() (io.ReadCloser, error) {
	if p == nil || p.cmd == nil {
		return nil, fmt.Errorf("process is nil")
	}
	pipe, err := p.cmd.StderrPipe()
	if err != nil {
		return nil, err
	}
	return &processEventReader{ReadCloser: pipe, process: p, stream: "stderr"}, nil
}

func (p *localProcess) SetOutput(stdout, stderr io.Writer) {
	if p == nil || p.cmd == nil {
		return
	}
	if p.sink == nil {
		p.cmd.Stdout = stdout
		p.cmd.Stderr = stderr
		return
	}
	p.cmd.Stdout = &processEventWriter{Writer: stdout, process: p, stream: "stdout"}
	p.cmd.Stderr = &processEventWriter{Writer: stderr, process: p, stream: "stderr"}
}

func (p *localProcess) Start() error {
	if p == nil || p.cmd == nil {
		return fmt.Errorf("process is nil")
	}
	p.mu.Lock()
	if p.start {
		p.mu.Unlock()
		return fmt.Errorf("process %s already started", p.id)
	}
	p.start = true
	p.mu.Unlock()

	p.eventMu.Lock()
	defer p.eventMu.Unlock()
	if err := p.cmd.Start(); err != nil {
		return err
	}
	tree, err := attachProcessTree(p.cmd)
	if err == nil {
		p.mu.Lock()
		p.tree = tree
		p.mu.Unlock()
	}
	// A missing process-tree capability must not prevent the shell itself from
	// running. Termination falls back to the platform's shell kill behavior.
	p.emitLocked(ProcessEventStarted, "", nil, nil)
	return nil
}

func (p *localProcess) Wait() error {
	if p == nil || p.cmd == nil {
		return fmt.Errorf("process is nil")
	}
	err := p.cmd.Wait()
	exit := processExitStatus(p.cmd.ProcessState, err)
	p.exitMu.Lock()
	p.exit = exit
	p.exitMu.Unlock()
	p.emit(ProcessEventExited, "", nil, exit)
	return err
}

func (p *localProcess) ExitStatus() *ExitStatus {
	if p == nil {
		return nil
	}
	p.exitMu.RLock()
	defer p.exitMu.RUnlock()
	if p.exit == nil {
		return nil
	}
	copy := *p.exit
	return &copy
}

func (p *localProcess) Terminate(_ context.Context) error {
	if p == nil || p.cmd == nil {
		return nil
	}
	p.mu.Lock()
	defer p.mu.Unlock()
	if p.cmd.Process == nil || p.cmd.ProcessState != nil {
		return nil
	}
	// Serialize termination with Close so a Windows Job Object cannot be
	// closed between reading the handle and terminating the process tree.
	terminateProcessTree(p.cmd, p.tree)
	p.emit(ProcessEventTerminateRequested, "", nil, nil)
	return nil
}

func (p *localProcess) Close() error {
	if p == nil {
		return nil
	}
	p.mu.Lock()
	if p.close {
		p.mu.Unlock()
		return nil
	}
	p.close = true
	tree := p.tree
	p.tree = nil
	p.mu.Unlock()
	closeProcessTree(tree)
	return nil
}

func (p *localProcess) emit(kind ProcessEventType, stream string, data []byte, exit *ExitStatus) {
	if p == nil || p.sink == nil {
		return
	}
	p.eventMu.Lock()
	defer p.eventMu.Unlock()
	p.emitLocked(kind, stream, data, exit)
}

func (p *localProcess) emitLocked(kind ProcessEventType, stream string, data []byte, exit *ExitStatus) {
	if p == nil || p.sink == nil {
		return
	}
	seq := atomic.AddUint64(&p.seq, 1)
	if len(data) > 0 {
		data = append([]byte(nil), data...)
	}
	if kind == ProcessEventOutput {
		p.outputBytes += int64(len(data))
	}
	p.sink(ProcessEvent{
		Type:        kind,
		ProcessID:   p.id,
		Seq:         seq,
		Context:     p.ctx,
		Stream:      stream,
		Data:        data,
		OutputBytes: p.outputBytes,
		Exit:        exit,
	})
}

func executionCommandDigest(command string) string {
	command = strings.TrimSpace(command)
	if command == "" {
		return ""
	}
	sum := sha256.Sum256([]byte(command))
	return hex.EncodeToString(sum[:])
}

func processExitStatus(state *os.ProcessState, err error) *ExitStatus {
	status := &ExitStatus{Code: -1}
	if state != nil {
		status.Code = state.ExitCode()
	}
	if err != nil {
		status.Error = err.Error()
	}
	return status
}

type processEventWriter struct {
	io.Writer
	process *localProcess
	stream  string
}

func (w *processEventWriter) Write(data []byte) (int, error) {
	n, err := w.Writer.Write(data)
	if n > 0 {
		w.process.emit(ProcessEventOutput, w.stream, data[:n], nil)
	}
	return n, err
}

type processEventReader struct {
	io.ReadCloser
	process *localProcess
	stream  string
}

func (r *processEventReader) Read(data []byte) (int, error) {
	n, err := r.ReadCloser.Read(data)
	if n > 0 {
		r.process.emit(ProcessEventOutput, r.stream, data[:n], nil)
	}
	return n, err
}
