<script setup>
import { onMounted, onUnmounted, ref } from "vue";
import { useRoute } from "vue-router";
import * as api from "../api/node.js";
import { agentStore } from "../stores/agent.js";
import { GOAL_TEMPLATES, formatGoalDate, goalBudgetRemaining, goalHasActiveRun, goalNextWakeLabel, goalReasonLabel, goalStatusLabel, goalStatusReason } from "../utils/goalPresentation.js";
const goals = ref([]); const selected = ref(null); const runs = ref([]); const error = ref(""); const notice = ref("");
const route = useRoute();
const terminalStatuses = new Set(["completed", "stopped", "failed"]);
const statusLabel = (goal) => goalStatusLabel(goal);
const runStatusLabel = (status) => ({ running: "执行中", completed: "已完成", failed: "失败", cancelled: "已取消", unknown: "用量未知" }[status] || status);
const runReasonLabel = (run) => goalReasonLabel({ status_reason: run?.reason }) || "—";
const draft = ref({ title: "", objective: "", acceptance: "", agent_id: String(agentStore.agentId || route.query.agent_id || ""), max_runs: 12, token_budget: 100000, turn_token_budget: 10000, min_wake_interval_seconds: 300, expires_at: "" });
const labels = { active: "运行中", paused: "已暂停", stopped: "已停止", completed: "已完成", waiting: "等待处理", failed: "失败" };
const templates = GOAL_TEMPLATES;
let refreshTimer;
const template = ref("observe");
function applyTemplate() { const item = templates[template.value]; if (item) Object.assign(draft.value, item); }
function needsApproval(goal) { const reason = goalStatusReason(goal).toLowerCase(); return goal?.status === "waiting" && Boolean(goal?.session_id) && /(approval|approv|hitl|human|审批|人工)/.test(reason); }
async function load() { try { const out = await api.listGoals(); const activeId = String(agentStore.agentId || draft.value.agent_id || "").trim(); goals.value = (out?.goals || []).filter((goal) => !activeId || String(goal.agent_id || "") === activeId); } catch (e) { error.value = e.message || "无法加载长期任务"; } }
async function open(goal) { error.value = ""; try { selected.value = await api.getGoal(goal.id); const out = await api.getGoalRuns(goal.id); runs.value = out?.runs || []; } catch (e) { error.value = e.message || "无法加载长期任务详情"; } }
async function action(name) { if (!selected.value) return; try { selected.value = await api.goalAction(selected.value.id, name); await open(selected.value); } catch (e) { error.value = e.message || "操作失败"; } }
async function wake() { if (!selected.value) return; error.value = ""; try { const out = await api.goalAction(selected.value.id, "wake"); notice.value = out?.delivery_id ? "已提交下一次运行，正在等待投递" : "已提交下一次运行"; await open(selected.value); } catch (e) { error.value = e.message || "唤醒失败"; } }
onMounted(() => { applyTemplate(); void load(); refreshTimer = setInterval(async () => { const before = selected.value?.status; await load(); if (selected.value?.id) await open(selected.value); const after = selected.value?.status; if (before && after && before !== after && ["completed", "waiting", "failed", "paused", "stopped"].includes(after)) notice.value = `任务状态已更新：${labels[after] || after}`; }, 15000); });
onUnmounted(() => { if (refreshTimer) clearInterval(refreshTimer); });
</script>
<template><div class="goals-page"><header><div><p class="eyebrow">当前 Agent：{{ agentStore.agentId || "未选择" }}</p><h1>长期任务</h1><p>让 Agent 分多次推进目标，保存进度并在需要时请求接管。</p><router-link v-if="agentStore.agentId" class="goal-back" :to="{ name: 'agents', params: { agentId: agentStore.agentId } }">返回 Agent 工作区</router-link></div></header><p v-if="error" class="goal-error" role="alert">{{ error }}</p><p v-if="notice" class="goal-notice" role="status">{{ notice }}</p><section class="goal-card goal-create-link"><h2>自主任务已迁移</h2><p>新建长期任务请创建 Auto Agent，在智能体设置中配置自主任务。此页保留历史运行记录。</p><router-link class="btn btn--primary" :to="{ name: 'settings-agents' }">前往智能体设置</router-link></section><section class="goal-columns"><div class="goal-card"><h2>任务列表</h2><button v-for="goal in goals" :key="goal.id" class="goal-row" :class="{active:selected?.id===goal.id}" @click="open(goal)"><strong>{{ goal.title }}</strong><span>{{ statusLabel(goal) }} · {{ goalHasActiveRun(goal) ? '执行中' : (goal.status === 'active' ? '待唤醒' : (goal.status === 'waiting' && goal.status_reason === 'approval_required' ? '等待审批' : (goal.status === 'paused' ? '后续运行已暂停' : '已结束'))) }} · {{ goal.runs }}/{{ goal.max_runs }} 次</span></button><p v-if="!goals.length">暂无长期任务</p></div><div v-if="selected" class="goal-card"><h2>{{ selected.title }}</h2><p>{{ selected.objective }}</p><p>完成条件：{{ selected.acceptance }}</p><p>状态：{{ statusLabel(selected) }} · 下次唤醒：{{ goalNextWakeLabel(selected) }}</p><p>剩余预算：{{ goalBudgetRemaining(selected).toLocaleString() }} tokens（单次模型请求可能超出预算阈值）<span v-if="goalReasonLabel(selected)"> · 原因：{{ goalReasonLabel(selected) }}</span></p><p v-if="selected.last_checkpoint?.summary">最新进度：{{ selected.last_checkpoint.summary }}</p><p v-if="selected.last_checkpoint?.evidence?.length">证据：{{ selected.last_checkpoint.evidence.join('；') }}</p><p v-if="selected.last_checkpoint?.artifacts?.length">产物：{{ selected.last_checkpoint.artifacts.join('；') }}</p><router-link v-if="selected.session_id" class="goal-session" :to="{ name: 'agents', params: { agentId: selected.agent_id }, query: { session_id: selected.session_id } }">打开专用会话</router-link><router-link v-if="needsApproval(selected)" class="goal-approval" :to="{ name: 'agents', params: { agentId: selected.agent_id }, query: { session_id: selected.session_id } }">去处理此会话中的审批</router-link><div v-if="!terminalStatuses.has(selected.status)" class="goal-actions"><button class="btn btn--ghost" @click="action(selected.status==='paused'?'resume':'pause')">{{ selected.status === 'paused' ? '继续' : '暂停' }}</button><button class="btn btn--ghost" @click="wake">立即运行</button><button class="btn btn--ghost" @click="action('stop')">停止</button></div><h3>运行历史</h3><ul><li v-for="run in runs" :key="run.id">{{ runStatusLabel(run.status) }} · {{ runReasonLabel(run) }} · {{ formatGoalDate(run.started_at) }}</li></ul></div></section></div></template>
<style scoped>.goals-page{width:min(1080px,100%);padding:28px}.goals-page header{margin-bottom:20px}.eyebrow{font-size:12px;color:var(--color-text-muted)}h1{margin:4px 0;font-size:24px}.goal-card{padding:20px;margin-bottom:20px;border:1px solid var(--color-border);border-radius:10px;background:var(--color-surface)}.goal-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:16px 0}.goal-grid label{display:grid;gap:6px;font-size:13px;color:var(--color-text-muted)}.goal-grid .wide{grid-column:1/-1}.goal-grid input,.goal-grid textarea{padding:8px;border:1px solid var(--color-border);border-radius:6px;background:var(--color-surface-elevated);color:var(--color-text);font:inherit}.goal-columns{display:grid;grid-template-columns:.9fr 1.4fr;gap:20px}.goal-row{display:grid;gap:5px;width:100%;padding:12px;border:0;border-bottom:1px solid var(--color-border);background:transparent;color:var(--color-text);text-align:left;cursor:pointer}.goal-row.active,.goal-row:hover{background:var(--color-surface-elevated)}.goal-row span,.goal-error{color:var(--color-text-muted);font-size:13px}.goal-actions{display:flex;gap:8px}@media(max-width:760px){.goal-grid,.goal-columns{grid-template-columns:1fr}.goal-grid .wide{grid-column:auto}}</style>
