<script setup>
import { computed, onMounted, ref, watch } from 'vue'

const props = defineProps({ agentId: { type: String, required: true } })
const emptyDraft = () => ({ source_id: '', root: '', revision: 1, enabled: true, hash_content: true })
const sources = ref([]); const draft = ref(emptyDraft()); const error = ref(''); const busy = ref(false); const loaded = ref(false); let epoch = 0; let mutationToken = 0
const endpoint = computed(() => `/v1/agents/${encodeURIComponent(props.agentId)}/event-sources`)
function readableError (body) { let text = String(body || '操作失败，请稍后重试'); try { const x = JSON.parse(text); text = String(x?.message || x?.error || x?.detail || text) } catch (_) {} return text.replace(/revision conflict/gi, '配置版本冲突，请刷新后重试').replace(/agent not found or not auto/gi, '找不到该 Agent，或它不是 Auto Agent').replace(/event store unavailable/gi, '事件源服务暂不可用') }
async function load () { const id = props.agentId; const e = ++epoch; loaded.value = false; try { const r = await fetch(endpoint.value); if (!r.ok) throw new Error(readableError(await r.text())); const data = await r.json(); if (id === props.agentId && e === epoch) { sources.value = data; loaded.value = true } } catch (x) { if (id === props.agentId && e === epoch) error.value = readableError(x.message) } }
async function save () { if (busy.value || !loaded.value) return; const id = props.agentId; const token = ++mutationToken; busy.value = true; error.value = ''; try { const r = await fetch(endpoint.value, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...draft.value, owner_agent_id: id }) }); if (!r.ok) throw new Error(readableError(await r.text())); if (id !== props.agentId || token !== mutationToken) return; draft.value = emptyDraft(); await load() } catch (x) { if (id === props.agentId && token === mutationToken) error.value = readableError(x.message) } finally { if (id === props.agentId && token === mutationToken) busy.value = false } }
async function change (source, method) { if (busy.value || !loaded.value) return; const id = props.agentId; const token = ++mutationToken; busy.value = true; error.value = ''; try { const url = method === 'DELETE' ? `${endpoint.value}/${encodeURIComponent(source.source_id)}?revision=${source.revision}` : endpoint.value; const body = method === 'POST' ? JSON.stringify({ ...source, enabled: !source.enabled, revision: Number(source.revision) + 1 }) : undefined; const r = await fetch(url, { method, ...(body ? { headers: { 'content-type': 'application/json' }, body } : {}) }); if (!r.ok) throw new Error(readableError(await r.text())) } catch (x) { if (id === props.agentId && token === mutationToken) error.value = readableError(x.message) } finally { if (id === props.agentId && token === mutationToken) { await load(); if (id === props.agentId && token === mutationToken) busy.value = false } } }
function toggle (source) { return change(source, 'POST') }; function remove (source) { return change(source, 'DELETE') }
onMounted(load)
watch(() => props.agentId, () => { ++epoch; ++mutationToken; sources.value = []; error.value = ''; busy.value = false; loaded.value = false; draft.value = emptyDraft(); load() })
</script>

<template>
  <section class="agent-event-sources-panel">
    <h3>事件源</h3><p class="hint">只读目录变化可触发 Auto Agent；每个事件源仅属于当前 Agent。</p>
    <div v-for="source in sources" :key="source.source_id" class="source-row"><div><strong>事件源：{{ source.source_id }}</strong><span>检测目录：{{ source.root }}</span><small>配置版本：{{ source.revision }} · {{ source.enabled ? '已启用' : '已停用' }}</small></div><div class="source-actions"><small v-if="source.state?.last_error" class="error">最近错误：{{ source.state.last_error }}</small><small v-if="source.state?.next_retry_at">下次重试：{{ source.state.next_retry_at }}</small><button class="btn btn--ghost btn--sm" :disabled="busy || !loaded" @click="toggle(source)">{{ source.enabled ? '停用' : '启用' }}</button><button class="btn btn--ghost btn--sm" :disabled="busy || !loaded" @click="remove(source)">删除</button></div></div>
    <form @submit.prevent="save"><label class="settings-field"><span class="settings-field__label">事件源名称</span><input v-model="draft.source_id" class="settings-field__input" placeholder="例如：项目目录" required></label><label class="settings-field"><span class="settings-field__label">检测目录</span><input v-model="draft.root" class="settings-field__input" placeholder="绝对目录路径" required></label><label class="settings-field"><span class="settings-field__label">检测内容</span><input v-model="draft.hash_content" class="settings-field__checkbox" type="checkbox"></label><button class="btn btn--primary add-source-button" :disabled="busy || !loaded">{{ busy ? '保存中…' : '添加事件源' }}</button></form>
    <p v-if="error" class="error">{{ error }}</p>
  </section>
</template>

<style scoped>
.agent-event-sources-panel{margin-top:20px;padding-top:16px;border-top:1px solid var(--border-subtle)}.hint,.source-row small,.source-row span{display:block;color:var(--text-secondary);font-size:12px}.source-row{display:flex;justify-content:space-between;gap:16px;padding:12px 0;border-bottom:1px solid var(--border-subtle)}.source-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap;justify-content:flex-end}.settings-field{display:grid;grid-template-columns:minmax(180px,1fr) minmax(220px,1.35fr);align-items:center;gap:20px;margin:0;padding:13px 0;border-bottom:1px solid var(--border-subtle)}.settings-field__label{color:var(--text-primary)}.settings-field__checkbox{width:18px;min-height:18px;justify-self:start}.add-source-button{justify-self:start;margin-top:14px}.error{color:var(--danger,#c44)}@media(max-width:640px){.settings-field{grid-template-columns:1fr;gap:8px}.source-row{align-items:flex-start;flex-direction:column}.source-actions{justify-content:flex-start}}
</style>
