<script setup>
import {computed,onMounted,ref,watch} from 'vue'
const finiteUsage = u => { const n = typeof u === 'number' ? u : Number(u?.maintenance_tokens); return u == null || u?.unknown || !Number.isFinite(n) ? '累计维护用量：待对账' : `累计维护用量：${n} tokens` }
const props=defineProps({agentId:{type:String,required:true}});const config=ref({maintenance_enabled:false,maintenance_schedule:'daily 09:00',timezone:'Asia/Shanghai',profile_revision:0});const loading=ref(false),saving=ref(false),running=ref(false),error=ref(''),loadError=ref(''),result=ref(null);let epoch=0
const endpoint=computed(()=>`/v1/agents/${encodeURIComponent(props.agentId)}/maintenance`),scheduleTime=computed({get:()=>String(config.value.maintenance_schedule||'').match(/(\d{2}:\d{2})$/)?.[1]||'',set:v=>config.value.maintenance_schedule=`daily ${v}`}),canOperate=computed(()=>!loading.value&&!saving.value&&!running.value&&Number(config.value.profile_revision)>0)
const usage=u=>u==null?'累计维护用量：待对账':typeof u==='number'?`累计维护用量：${u} tokens`:u.unknown?'累计维护用量：待对账':`累计维护用量：${Number(u.maintenance_tokens)} tokens`;const msg=(b,f)=>{try{const x=JSON.parse(b);return String(x?.message||x?.error||f)}catch(_){return String(b||f)}}
async function load(){const id=props.agentId,e=++epoch;loading.value=true;loadError.value='';error.value='';result.value=null;try{const r=await fetch(endpoint.value);if(!r.ok)throw Error(msg(await r.text(),'维护配置加载失败'));const d=await r.json();if(id===props.agentId&&e===epoch)config.value={...config.value,...d}}catch(x){if(id===props.agentId&&e===epoch)loadError.value=msg(x.message,'维护配置加载失败')}finally{if(id===props.agentId&&e===epoch)loading.value=false}}
async function save(){if(!canOperate.value)return;const id=props.agentId,e=++epoch;saving.value=true;error.value='';try{const r=await fetch(endpoint.value,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({maintenance_enabled:config.value.maintenance_enabled,maintenance_schedule:config.value.maintenance_schedule,timezone:config.value.timezone,expected_revision:config.value.profile_revision})});if(!r.ok)throw Error(msg(await r.text(),'维护配置保存失败'));const d=await r.json();if(id===props.agentId&&e===epoch)config.value={...config.value,...d}}catch(x){if(id===props.agentId&&e===epoch)error.value=msg(x.message,'维护配置保存失败')}finally{if(id===props.agentId&&e===epoch)saving.value=false}}
async function run(){if(!canOperate.value)return;const id=props.agentId,e=++epoch;running.value=true;error.value='';result.value=null;try{const r=await fetch(`${endpoint.value}/run`,{method:'POST'});if(!r.ok)throw Error(msg(await r.text(),'维护运行失败'));const d=await r.json();if(id===props.agentId&&e===epoch)result.value=d}catch(x){if(id===props.agentId&&e===epoch){error.value=msg(x.message,'维护运行失败');result.value={error:error.value}}}finally{if(id===props.agentId&&e===epoch)running.value=false}}
onMounted(load);watch(()=>props.agentId,()=>{++epoch;config.value={maintenance_enabled:false,maintenance_schedule:'daily 09:00',timezone:'Asia/Shanghai',profile_revision:0};load()})
</script>
<template><section class="agent-maintenance-panel"><div class="maintenance-heading"><div><span class="settings-kicker">维护</span><h3>自动维护</h3></div></div><p v-if="loading" class="hint">加载中…</p><div v-else-if="loadError" class="maintenance-load-error"><p class="error" role="alert">{{loadError}}</p><button class="btn btn--ghost" @click="load">重新加载</button></div><template v-else><p class="hint">下一次维护：{{config.next_at?new Date(config.next_at).toLocaleString():'未安排'}} · 最近结果：{{config.last?.status||'暂无记录'}} · {{usage(config.usage)}}</p><label class="settings-field"><span>启用维护</span><input v-model="config.maintenance_enabled" type="checkbox"/></label><label class="settings-field"><span>每天运行时间</span><input v-model="scheduleTime" type="time"/></label><label class="settings-field"><span>时区</span><input v-model="config.timezone" type="text"/></label><div class="maintenance-actions"><button class="btn btn--ghost" :disabled="!canOperate" @click="save">{{saving?'保存中…':'保存维护设置'}}</button><button class="btn btn--primary" :disabled="!canOperate" @click="run">{{running?'运行中…':'立即运行维护'}}</button></div><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="result&&!result.error" class="maintenance-result">本次维护已完成。 {{usage(result.usage)}}</p></template></section></template>
<style scoped>.agent-maintenance-panel{margin-top:20px;padding-top:16px;border-top:1px solid var(--border-subtle)}.maintenance-heading{display:flex;justify-content:space-between}.maintenance-heading h3{margin:3px 0}.settings-kicker,.hint{color:var(--text-secondary);font-size:12px}.settings-field{display:grid;grid-template-columns:1fr 1.35fr;padding:13px 0;border-bottom:1px solid var(--border-subtle)}.maintenance-actions{display:flex;gap:10px;margin-top:14px}.maintenance-load-error{display:flex;gap:12px}.error{color:var(--danger,#c44)}.maintenance-result{padding:12px;background:var(--surface-subtle,rgba(127,127,127,.08))}</style>
